### ISSUE TITLE
次回の集合研修実施時期

### ISSUE THREAD

**Issue by kyosukem** [M2O-Workshop/Training#12]
2月にするか3月にするか相談です。

2月にすると、Aflacで本番移行が予定されていて、負荷が高くなる懸念があります。
3月にすると、その後の4，5月と毎月開催になる可能性があります。

考え方次第ですが、2月は準備期間に充てて、後半に追い込みでやる、というのはどうですかね？
（3月開催案です）

ご意見プリーズ！

**Comment by yamamoto-t** [comment]
現在のHOST（特に金融1G）メンバの稼働の高さも考慮すると、3月開催案で良いと思います。

ただ、懸念として、
　・前回（01/14）から約2か月、間が空く。
　・次回からは扱う題材が変わる予定。
といった点から、Web基礎の理解が中途半端なままになりそうです。

また、先日の集合研修ではDBやJava基礎もだいぶ忘れているorそもそも必須の演習が未完了、
という受講者が多いと感じました。**得た知識が断片的で、脳内で連結されていない**という印象です。

このまま業務アプリ開発に進んだ場合、**コアからのコピペ開発すら厳しい**かも知れません。
<br>
そこで例えばですが2月の断面で、
　・受講生側・・・これまでの演習について完了分をすべてcommit&push。
　　　⇒各自で『不安箇所』（消化率の悪い演習や、特に理解が浅いと思う要素）も提示できると良い。
　　↓↓
　・運営側・・・Gitの受講生リポジトリを元に演習の進捗状況を一覧化し、受講生に展開。
　　　　　　　　特に消化率の悪い単元は追加で資料を作成する、といったフォローも検討する。
　　↓↓
　・受講生側・・・フォローも受けつつ、未了の演習を進める。

等、**受講生からのFeedbackに基づいた能動的な対策**を講じた方が良いかと思います。
（進捗一覧作成とレビュの集中により、運営側の負荷が高くなる可能性あり。）

※思い付きですが、演習の進捗管理も可能ならいずれ**Gitと連動させWebアプリ化**したく。
　もし公式のAPIがあれば実装の敷居も低く、運営側で都度リポジトリを目検せず済みます。

**Comment by kyosukem** [comment]
まず、3月開催で確定しましょう。

2月は既存演習の各自の復習に充てますかね。
で、山本氏案の通り、GitHub への push で進捗を測りましょう。LINEで周知します。
LINEでの周知の際に、現時点の状況を可視化できますかね？
2月末での完了を目指し、自宅学習を促す材料になれば。

進捗管理のWebアプリ化も面白いですね。これを課題にするのもいいかも。

**Comment by kyosukem** [comment]
先ほど山本相談しました。
3/11（土）の開催で仮決めします。
ネタは以下の通り。
・先発組はpracticeOOPを使用した解説＆演習
・若生は後発組に混ざって、皆川解説によるServlet/JSPの学習
・後発組はJava基礎＆DBの演習を継続

2月中は空いてしまいますが、先発組はServlet/JSPの学習を自宅にて済ませるよう、アナウンスします。

なお、practiceOOPを使用した解説＆演習の内容については、
practiceOOPリポジトリのissueで議論します。
