### ISSUE TITLE
Traningリポジトリの分割

### ISSUE THREAD

**Issue by kyosukem** [M2O-Workshop/Training#13]
現在、Traningリポジトリは３つのアプリケーションが同居しています。
アプリケーション毎にリポジトリを分割するのはどうでしょう？
（実際には、practiceOOPだけ別リポジトリに切り出す）

意図は以下。
次回の集合研修はpracticeOOPを使用した解説・演習になると思いますが、
受講メンバへのソース展開をするうえで、どうしようかと。
やり方の案です。
1.研修課題に使用する「practiceOOP」は別リポジトリに切り出して、扱いやすくる
2.M2O-Workshopのmemberにm2oGITアカウントを参加させる
3.研修では、各自m2oGITアカウントでpracticeOOPリポジトリをクローンする

**Comment by yamamoto-t** [comment]
確かに、現在の構成だとeclipseのworkspaceへのインポートにひと手間挟みますからね。
近い内に「practiceOOP」を個別のリポジトリに切り出しておきます。

「やり方の案」についてもご提示の内容ベースで良いと思います。

なお、「practiceOOPリポジトリをクローン」後、各自で演習を実施しそのままcommit&pushすると
同一のmasterを上書きしてしまいます。

受講生毎に別名でbranchを切ってcommit&pushして貰うか、
一度共有を「切断」した後で平時の演習で使用している個人リポジトリに繋ぎ直すか、多少工夫が必要です。

**Comment by kyosukem** [comment]
practiceOOP をどのようにメンバに配布するか、また、GitHubでの各自の管理をどうするか、課題ですね。

ブランチだとやりづらいかな。。。リポジトリを各自用にforkするのはどうですかね？演習問題用リポジトリみたいに、自分用のpracticeOOPを用意するイメージです。
いっそのこと、GitHubアカウントをつくってもらうのもありかな。。。

**Comment by yamamoto-t** [comment]
ひとまず、practiceOOPをM2O-Workshop配下の新規個別リポジトリに移設しました。
ここまでの履歴はメンバには不要なので、きれいさっぱりクリアした状態ですが、
念のため、Training配下のpracticeOOPは未だ残してあります。
https://github.com/M2O-Workshop/practiceOOP.git

上記URLをEgitの「リポジトリの複製」に貼り付けて、
「クローン終了後、全てのeclipseプロジェクトをインポートする」にチェックを入れておくと
workspaceへのインポートまでが自動的に完了します。

あとは右クリックから「Mavenプロジェクトの更新」「Maven clean」「Maven install」を順に実行すれば
環境構築も完了し、「サーバーで実行」で起動する筈です（サーバーランタイム設定のみは適宜手動で実施）。
茂木さんのイメージに合っておりますでしょうか？？
<br>
配布後の管理についてはforkでも良いですし、クローン後に一度切断してから
いつもの演習用個人リポジトリに繋ぎ直す（プロジェクトの共用→commit&push）でも良いかと。
メンバも使用している共用Gitアカウントを使い、山本リポジトリでクローン～起動まで検証済みです。
https://github.com/m2oGIT/T_YamamotoRepository.git

手順として解り易い半面、見ての通り、演習用個人リポジトリが少々ごちゃつくのが難点です。

**Comment by kyosukem** [comment]
対応ありがとう！確認しました。
イメージあっています。

>配布後の管理についてはforkでも良いですし、クローン後に一度切断してから
>いつもの演習用個人リポジトリに繋ぎ直す（プロジェクトの共用→commit&push）でも良いかと。
配布方法はこれで行きましょう。

practiceOOPの演習に関する議論は、practiceOOPリポジトリのissueで管理することにします。
